### ISSUE TITLE
Modules not responding to Gestures after Update MM / fresh install

### ISSUE THREAD

**Issue by SaschaSp** [thobach/MMM-Gestures#18]
After Update to MagicMirror 2.19.0  News& Compliments not responding to Gestures.
Try a fresh install from MMM-Gestures & also MagicMirror, same behavior.
Checked that /dev/ttyUSB0 within node_helper.js set right.
Sensors are working, checked with screen /dev/ttyUSB0 9600.
pm2 logs shows:
0|MagicMirror  | [04.04.2022 13:10.44.503] [ERROR]
0|MagicMirror  | TypeError: SerialPort is not a constructor
0|MagicMirror  |     at /home/pi/MagicMirror/modules/MMM-Gestures/node_helper.js:117:25
0|MagicMirror  |     at ChildProcess.exithandler (node:child_process:397:7)
0|MagicMirror  |     at ChildProcess.emit (node:events:390:28)
0|MagicMirror  |     at maybeClose (node:internal/child_process:1064:16)
0|MagicMirror  |     at Socket.<anonymous> (node:internal/child_process:450:11)
0|MagicMirror  |     at Socket.emit (node:events:390:28)
0|MagicMirror  |     at Pipe.<anonymous> (node:net:687:12)

**Comment by Tom-Hirschberger** [comment]
Hi, had the same issue with my module (Thank you @SaschaSp; Would not have noticed without you contacting me and creating this issue).
The syntax of the declaration of SerialPort and ReadLineParser changed.
I opened an pull request which should fix the issue.
#19

**Comment by thobach** [comment]
Should be resolved now thanks to the fix from @Tom-Hirschberger.

**Comment by SaschaSp** [comment]
Working great again, Thanks @Tom-Hirschberger and @thobach
