### ISSUE TITLE
Serialport version issue

### ISSUE THREAD

**Issue by christopolise** [thobach/MMM-Gestures#3]
Trying to use the hardware for this project, I ran into the following error:

`readline is not a function`

in gestures.js. This appears to be a dependency issue with `serialport`. The version this project uses is `4.x.x` and the current one installed by npm is `9.x.x`. After going through dependency hell, it appears that changing the current syntax to match the current version of `serialport` is the easiest fix...

**Comment by thobach** [comment]
Thanks @christopolise for the pull-request PR#4. I had addressed the issue amongst others already earlier and needed more time for testing first. The changes are now published and you can find the delta in e9f4ab7, hence I'll close this issue.
