### ISSUE TITLE
Support for MMM-SmartWebDisplay

### ISSUE THREAD

**Issue by McMornan** [thobach/MMM-Gestures#9]
Hi, 

works like a charm, thanks !

I added support for the module above by adding 

`
 var smartwebdisplay = MM.getModules().withClass('MMM-SmartWebDisplay');

                if(smartwebdisplay){

                        var notification = "UNKNOWN";

                        // reverting orders since sensor is usually built in upside down
                        if(payload == 'LEFT'){
                                notification = "SWD_PREV";
                        } else if(payload == 'RIGHT'){
                                notification = "SWD_NEXT";
                        } else if(payload == 'UP'){
                                notification = "SWD_PLAY";
                        } else if(payload == 'DOWN'){
                                notification = "SWD_PAUSE";
                        } else {
                                Log.info('Not handling received gesture in this module directly:');
                                Log.info(payload);
                        }
`
            at the end of MMM-Gestures.js

Would be nice if you could incorporate it in further releases.      

I am lazy and tend to forget what I changed before pulling :)

Cheers,
Lars

**Comment by thobach** [comment]
Hi Lars, Thanks for your contribution. Could you please create a pull request with your change and exten the documentation accordingly? Thanks!
